### ISSUE TITLE
Retry handling on `EXPECTED_FAILED` tests

### ISSUE THREAD

**Issue by martingrossmann** [telekom/testerra#180] opened 2021-11-29 15:46 UTC
**Is your feature request related to a problem? Please describe.**
At the moment there is no retry on expected fails. It is assumed that a known bug needs no retry. With the refactoring of the `RetryAnalyzer` there are definded some general retry causes like `WebDriverExceptions`

**Describe the solution you'd like**
The retry handling could also be active at `EXPECTED_FAILED` tests. A `WebDriverException` is also a good cause of a retry independed of a `@Fails` annotation.

**Comment by mreiche** [comment] 2021-12-01 08:52
Duplicate of https://github.com/telekom/testerra/issues/165

**Closed by mreiche** 2021-12-01 08:52 UTC
Labels: enhancement
