### ISSUE TITLE
Page creation should only fail after all elements have been checked instead of failing after the first failed check

### ISSUE THREAD

**Issue by sbke-mms** [telekom/testerra#212] opened 2022-02-16 12:32 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when elements on a page get changed and a page creation only fails on the first change instead of pointing out all changes.

**Describe the solution you'd like**
Page creation should check all elements that are annotated with `@Check` and if it fails give a list of all elements where the check failed.

**Describe alternatives you've considered**
If this can't or shouldn't be done implicitly for some reason then make it available via an extra parameter on the existing `@Check` annotation or a new annotation (maybe for the page class).

**Comment by mreiche** [comment] 2022-02-21 15:42
Duplicate of https://github.com/telekom/testerra/issues/207

**Closed by mreiche** 2022-02-21 15:42 UTC
Labels: enhancement
